#!/usr/bin/env python3
"""
Pending Review Prompt — SessionStart hook.

Checks ~/.claude/.pending-skills/pending/ for proposals generated by the
background Stop-hook review. If any exist, prints a message so the user sees
it at session start.
"""

import json
import sys
from pathlib import Path

PENDING_DIR = Path.home() / ".claude" / ".pending-skills" / "pending"
APPROVED_DIR = Path.home() / ".claude" / ".pending-skills" / "approved"
REJECTED_DIR = Path.home() / ".claude" / ".pending-skills" / "rejected"


def _list_proposals():
    if not PENDING_DIR.exists():
        return []
    proposals = sorted(PENDING_DIR.glob("*.json"))
    return proposals


def _summarize(path: Path) -> str:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        name = data.get("name", "unknown")
        action = data.get("action", "create")
        reason = data.get("reason", "")
        return f"  - {name} ({action}): {reason[:80]}"
    except Exception:
        return f"  - {path.name} (unreadable)"


def main():
    proposals = _list_proposals()
    if not proposals:
        return 0

    print(f"\n🧠 Pending skill reviews: {len(proposals)}")
    for p in proposals:
        print(_summarize(p))
    print("\nTo approve or reject, ask me: 'show pending skill reviews'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
